import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { OrderModel, OrderStatus } from '../../model/Order-model'
import { ApiCaller } from '../../utils/ApiCaller'
import { RootState } from '../../app/store'

interface OrderDbState {
  orders: OrderModel[]
  status: 'idle' | 'loading' | 'failed'
}

const initialState: OrderDbState = {
  orders: [],
  status: 'idle'
}

export const getActiveOrderDb = createAsyncThunk(
  'orderDb/get',
  async (): Promise<OrderModel[]> => {
    const filters = { status: [OrderStatus.NEW, OrderStatus.PARTIALLY_FILLED] }
    return await ApiCaller.getOrderFromDb(filters)
  }
)
export const orderDbSlice = createSlice({
  name: 'orderDb',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    updateOrders: (state, action) => {
      state.orders = action.payload
    }
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getActiveOrderDb.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(getActiveOrderDb.fulfilled, (state, action) => {
        state.status = 'idle'
        state.orders = action.payload
      })
  }
})

export const { updateOrders } = orderDbSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectOrdersDb = (state: RootState): OrderModel[] => {
  return state.orderDb.orders
}

export default orderDbSlice.reducer
