import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { ApiCaller } from '../../utils/ApiCaller'
import { RootState } from '../../app/store'
import { PlanModel } from '../../model/PlanModel'

interface OrderDbState {
  planSelected: string | null
  plans: PlanModel[]
  status: 'idle' | 'loading' | 'failed'
}

const initialState: OrderDbState = {
  planSelected: null,
  plans: [],
  status: 'idle'
}

export const fetchPlans = createAsyncThunk(
  'plans/get',
  async (): Promise<PlanModel[]> => {
    console.log('fetchPlans')
    const plans = await ApiCaller.getPlans()
    console.log('plans', plans)
    return plans
  }
)
export const planSlice = createSlice({
  name: 'orderDb',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    selectPlan: (state, action) => {
      state.planSelected = action.payload
    }
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchPlans.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(fetchPlans.fulfilled, (state, action) => {
        state.status = 'idle'
        state.plans = action.payload
      })
  }
})

export const { selectPlan } = planSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const planSelected = (state: RootState): PlanModel | null => {
  console.log('planSelected', state)
  for (const plan of state.plan.plans) {
    if (plan._id === state.plan.planSelected) {
      return plan
    }
  }
  return null
}
export const allPlans = (state: RootState): PlanModel[] => {
  return state.plan.plans
}

export default planSlice.reducer
